# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160725_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='user',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
