# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20160801_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
