# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160804_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='roast_title',
            field=models.CharField(default='Question', max_length=20),
        ),
    ]
