# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_roast_roast_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roast',
            name='roast_title',
            field=models.CharField(default='Question', max_length=200),
        ),
    ]
