# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160805_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='roast_choice',
            field=models.CharField(default='Choice', max_length=200),
        ),
    ]
