# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
    ]
