# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_choice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='poll',
            new_name='question',
        ),
    ]
